spring.application.name=fraud-engine-service
server.port=8092

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.root=INFO
logging.level.com.se.frms.fraudengine=INFO

spring.kafka.bootstrap-servers=127.0.0.1:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Gives the producer time to obtain Kafka topic metadata during service startup.
spring.kafka.producer.properties.max.block.ms=5000
frms.kafka.topic.fraud-events=frms.fraud-events
frms.rule-cache.base-url=http://localhost:8093
frms.rule-cache.active-rules-path=/api/v1/rules/active
frms.rule-cache.refresh-interval-ms=30000
frms.scoring.base-url=http://localhost:8094
frms.scoring.path=/api/v1/scoring
frms.decision.base-url=http://localhost:8095
frms.decision.path=/api/v1/decisions
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

logging.file.name=logs/fraud-engine-service.log
