spring.application.name=fraud-engine-service
server.port=8092

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.root=INFO
logging.level.com.se.frms.fraudengine=INFO

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
frms.kafka.topic.fraud-events=frms.fraud-events
frms.rule-cache.base-url=http://rule-cache-service
frms.rule-cache.active-rules-path=/api/v1/rules/active
frms.scoring.base-url=http://scoring-service
frms.scoring.path=/api/v1/scoring
frms.decision.base-url=http://decision-service
frms.decision.path=/api/v1/decisions
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

